version: "3.8"

services:
  blue:
    build:
      context: ./blue-app
    container_name: blue_app
    ports:
      - "8081:80"

  green:
    build:
      context: ./green-app
    container_name: green_app
    ports:
      - "8082:80"

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - blue
      - green